version: '2'
services:
  db:
    image: mariadb:latest
    container_name: pretix_db
    environment:
      - MYSQL_DATABASE=pretix
      - MYSQL_USER=pretix
      - MYSQL_PASSWORD=pretix
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: pretix_redis

  pretix_base:
    build: .
    volumes:
      - pretix-data:/data

  pretix_web:
    extends: pretix_base
    container_name: pretix_web
    depends_on:
      - db
      - redis
    command: ./docker-entrypoint.sh
    volumes:
      - static-data:/pretix/src/pretix/static.dist

  pretix_task:
    extends: pretix_base
    container_name: pretix_task
    depends_on:
      - pretix_web
    environment:
      - C_FORCE_ROOT=True
    command: celery -A pretix.celery_app worker -l info

  nginx:
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - static-data:/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - pretix_web

volumes:
  pretix-data:
  static-data:
  db-data:
