version: '2'
services:
  db:
    image: mariadb:latest
    container_name: pretix_db
    environment:
      - MYSQL_DATABASE=pretix
      - MYSQL_USER=pretix
      - MYSQL_PASSWORD=pretix
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: pretix_redis
    networks:
      - backend

  pretix_base:
    build: .
    volumes:
      - pretix-data:/data
    networks:
      - backend

  pretix_web:
    extends: pretix_base
    container_name: pretix_web
    depends_on:
      - db
      - redis
    command: ./docker-entrypoint.sh
    volumes:
      - static-data:/pretix/src/pretix/static.dist
      - ./pretix.cfg:/etc/pretix/pretix.cfg
    networks:
      - backend

  pretix_task:
    extends: pretix_base
    container_name: pretix_task
    depends_on:
      - pretix_web
    environment:
      - C_FORCE_ROOT=True
    command: celery -A pretix.celery_app worker -l info
    volumes:
      - ./pretix.cfg:/etc/pretix/pretix.cfg
    networks:
      - backend

  nginx:
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - static-data:/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - pretix_web
    networks:
      - backend
      - frontend-web
    env_file: frontend.env

volumes:
  pretix-data:
  static-data:
  db-data:

networks:
  frontend-web:
    external: true
  backend:
    driver: bridge
